### PR TITLE
Fix Mingw compiler errors

### LINKED ISSUE #3: Fix extra qualifications on class member functions
Functions affected:
`DisasterHelper::IsLocInSafeArea`
`DisasterHelper::FindVortexEndLoc`
`FightGroupMaker::TestGuardingHoldingZone`

### LINKED ISSUE #4: Use platform independent path separators
A few `#include` lines use the Windows specific `\` path separator, rather than the platform independent `/` path separator (which most of the project uses).

DisasterHelper.h:
```
#include "OP2Helper\OP2Helper.h"
#include "Outpost2DLL\Outpost2DLL.h"
```

FightGroupMaker.cpp:
```
#include "HFL\Source\HFL.h"
```

Fixing these allows the code to be checked on Linux with the Mingw compiler.

### LINKED ISSUE #5: Add missing array include
DisasterHelper.h uses `std::array` for a method parameter, but has no `#include <array>`.

### LINKED ISSUE #6: FightGroup::SetRect is not able to bind to rvalues
In Outpost2DLL, the `FightGroup::SetRect` method is defined to take a non-`const` lvalue reference:
```cpp
void SetRect(MAP_RECT& idleRect);
```

Methods taking non-`const` lvalue references do not bind to calls with rvalue arguments, as per standard C++. MSVC has a non-standard extension that allows it.

To make the code standard conforming, the temporary rvalue should first be captured in a variable, and then the variable should be passed.

This affects FightGroupMaker.cpp in two places.

FightGroupMaker.cpp: line 313:
```cpp
	fightGroup.SetRect(MAP_RECT(
		building.Location().x - 5, building.Location().y - 5,
		building.Location().x + 5, building.Location().y + 5));
```

Suggestion:
```cpp
	MAP_RECT mapRect(
		building.Location().x - 5, building.Location().y - 5,
		building.Location().x + 5, building.Location().y + 5
	);
	fightGroup.SetRect(mapRect);
```

FightGroupMaker.cpp: line 415:
```cpp
	fightGroupHoldingZone.SetRect(MAP_RECT (162 + X_, 1 + Y_, 190 + X_, 7 + Y_));
```

Suggestion:
```cpp
	MAP_RECT mapRect(162 + X_, 1 + Y_, 190 + X_, 7 + Y_);
	fightGroupHoldingZone.SetRect(mapRect);
```

### PR DESCRIPTION
**Pull request by Brett208**
Closes #3
Closes #4
Closes #5
Closes #6

### CODE REVIEW

File: DisasterHelper.h [hunk 1]
```diff
@@ -2,11 +2,12 @@
...
 // Disaster Helper Version: 1.0
 
-#include "OP2Helper\OP2Helper.h"
-#include "Outpost2DLL\Outpost2DLL.h"
+#include "OP2Helper/OP2Helper.h"
+#include "Outpost2DLL/Outpost2DLL.h"
 #include <climits>
 #include <cmath>
 #include <vector>
+#include <array>
```
Comment (DanRStevens) [inline DisasterHelper.h:10]: Really minor point: this line has a trailing whitespace.
